<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-12-29">

<title>iaingallagher.github.io - Probability and Bayes Rule</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">iaingallagher.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Probability and Bayes Rule</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">Bayes</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 29, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This is the first of a series of posts going over the basics of Bayesian inference. Bayesian inference uses Bayes rule which comes from simple algebra of basic probability rules. In this post we’ll look at the basic rules of probability and derive Bayes rule. We’ll look at a couple of simple examples to see how Bayes rule works.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>There’s a little bit of <code>R</code> code in this post and I’m using the new native <code>R</code> pipe <code>|&gt;</code>. If you’re used to <code>tidyverse</code> semantics you might think that <code>|&gt;</code> behaves like the <code>magrittr</code> pipe, <code>%&gt;%</code> but it doesn’t! But it can (mostly) be used in the same way. See <a href="https://ivelasq.rbind.io/blog/understanding-the-r-pipe/">here</a> for more details.</p>
</div>
</div>
</section>
<section id="on-the-way-to-bayes-rule" class="level1">
<h1>On the way to Bayes rule</h1>
<p>The grade classifications for a course I taught in my previous job are shown in the table below. The course was taken by students across two programmes.</p>
<table class="table">
<caption>Table 1: Grade classification by programme.</caption>
<thead>
<tr class="header">
<th></th>
<th>Programme</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grade</strong></td>
<td>SES</td>
<td>SS</td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>3</td>
</tr>
<tr class="odd">
<td>2.1</td>
<td>20</td>
<td>6</td>
</tr>
<tr class="even">
<td>2.2</td>
<td>11</td>
<td>15</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>20</td>
</tr>
</tbody>
</table>
<p>Tables like this are called <em>contingency</em> tables and they are used to summarise the relationship between two (or more) categorical variables. We can create contingency tables in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dimnames is a list; rownames then colnames; |&gt; is native R pipe; pipe matrix to as.table func</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>grade_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">11</span>,<span class="dv">4</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">15</span>,<span class="dv">20</span>), <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">FALSE</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2.1"</span>, <span class="st">"2.2"</span>, <span class="st">"3"</span>), <span class="fu">c</span>(<span class="st">"SES"</span>, <span class="st">"SS"</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.table</span>()</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>              </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>grade_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    SES SS
1    10  3
2.1  20  6
2.2  11 15
3     4 20</code></pre>
</div>
</div>
<p>We can use contingency tables to calculate different types of probabilities.</p>
<section id="marginal-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="marginal-probabilities">Marginal probabilities</h2>
<p>The row and column totals for each variable in the table are called the <em>marginal</em> totals.</p>
<table class="table">
<caption>Table 2. Grade classifications with marginal totals</caption>
<thead>
<tr class="header">
<th></th>
<th>Programme</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grade</strong></td>
<td>SES</td>
<td>SS</td>
<td><strong>Marginal Total</strong></td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>3</td>
<td>13</td>
</tr>
<tr class="odd">
<td>2.1</td>
<td>20</td>
<td>6</td>
<td>26</td>
</tr>
<tr class="even">
<td>2.2</td>
<td>11</td>
<td>15</td>
<td>26</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>20</td>
<td>24</td>
</tr>
<tr class="even">
<td><strong>Marginal Total</strong></td>
<td>45</td>
<td>44</td>
<td>89</td>
</tr>
</tbody>
</table>
<p>We can get R to add marginal totals to contingency tables for us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>grade_table_marginals <span class="ot">&lt;-</span> grade_table <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>grade_table_marginals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    SES SS Sum
1    10  3  13
2.1  20  6  26
2.2  11 15  26
3     4 20  24
Sum  45 44  89</code></pre>
</div>
</div>
<p>The marginal totals can be used to calculate <em>marginal</em> probabilities by dividing the <span style="color: #00BFFF;">marginal</span> total for a row or column by the <span style="color: #00008B;">grand</span> total. We denote marginal probabilities as <span class="math inline">\(P(A)\)</span> where <span class="math inline">\(A\)</span> is some outcome.</p>
<p>For example the marginal probability of students getting a 2.1 is the marginal number of students who got a 2.1 (26) divided by the total number of students in the course (89).</p>
<p><span class="math display">\[
P(2.1) = \textcolor{#00BFFF}{26}/\textcolor{#00008B}{89} = 0.29
\]</span></p>
<table class="table">
<caption>Table 3. Numbers involved in marginal probabilities are coloured.</caption>
<thead>
<tr class="header">
<th></th>
<th>Programme</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grade</strong></td>
<td>SES</td>
<td>SS</td>
<td><strong>Marginal Total</strong></td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>3</td>
<td>13</td>
</tr>
<tr class="odd">
<td>2.1</td>
<td>20</td>
<td>6</td>
<td><span style="color: #00BFFF;">26</span></td>
</tr>
<tr class="even">
<td>2.2</td>
<td>11</td>
<td>15</td>
<td>26</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>20</td>
<td>24</td>
</tr>
<tr class="even">
<td><strong>Marginal Total</strong></td>
<td>45</td>
<td>44</td>
<td><span style="color: #00008B;">89</span></td>
</tr>
</tbody>
</table>
<p>We see that <span class="math inline">\(P(2.1)\)</span> is 29%.</p>
</section>
<section id="joint-probabilties" class="level2">
<h2 class="anchored" data-anchor-id="joint-probabilties">Joint probabilties</h2>
<p>The probability of two (or more) outcomes considered together is called a <em>joint</em> probability.</p>
<p>For events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> joint probabilities are often written as <span class="math inline">\(P(A \text{ } and \text{ } B)\)</span> or <span class="math inline">\(P(A, \text{ } B)\)</span>.</p>
<p>To calculate joint probability we divide <span style="color: #00BFFF;">the number of outcomes that fulfill a specific criteria</span> by the <span style="color: #00008B;">grand total</span>.</p>
<p>Here an example might be:</p>
<p><span class="math display">\[
P(2.1 \text{ and } SES)
\]</span></p>
<p>We can calculate this probability from the total number of SES students who got a 2.1 classification (20) divided by the total number of students (89).</p>
<p><span class="math display">\[
P(2.1 \text{ and } SES) = \textcolor{#00BFFF}{20}/\textcolor{#00008B}{89} = 0.225
\]</span></p>
<table class="table">
<caption>Table 4. Numbers involved in joint probabilities are coloured.</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 35%">
<col style="width: 5%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Programme</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grade</strong></td>
<td>SES</td>
<td>SS</td>
<td><strong>Marginal Total</strong></td>
</tr>
<tr class="even">
<td>1</td>
<td>10</td>
<td>3</td>
<td>13</td>
</tr>
<tr class="odd">
<td>2.1</td>
<td><span style="color: #00BFFF;">20</span></td>
<td>6</td>
<td>26</td>
</tr>
<tr class="even">
<td>2.2</td>
<td>11</td>
<td>15</td>
<td>26</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>20</td>
<td>24</td>
</tr>
<tr class="even">
<td><strong>Marginal Total</strong></td>
<td>45</td>
<td>44</td>
<td><span style="color: #00008B;">89</span></td>
</tr>
</tbody>
</table>
<p>We see that the joint probability of 2.1 and being on the SES programme is 22.5%.</p>
<p>For joint probabilities the order of the outcomes doesn’t matter.</p>
<p><span class="math inline">\(P(A \text{ and } B)\)</span> = <span class="math inline">\(P(B \text{ and } A)\)</span></p>
<p>In R the <code>prop.table()</code> function can convert a contingency table of raw numbers to a table of joint probabilities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>grade_probs <span class="ot">&lt;-</span> grade_table <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>() <span class="sc">|&gt;</span> <span class="co"># add marginal totals</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>) <span class="co"># round to 3dp</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>grade_probs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      SES    SS   Sum
1   0.112 0.034 0.146
2.1 0.225 0.067 0.292
2.2 0.124 0.169 0.292
3   0.045 0.225 0.270
Sum 0.506 0.494 1.000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Key to both marginal and joint probability is that we use the <strong>grand total</strong> as the denominator to calculate these probabilities.</p>
</div>
</div>
</section>
<section id="conditional-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="conditional-probabilities">Conditional probabilities</h2>
<p>Conditional probability is the probability of <span style="color: #00BFFF;">an event or outcome occurring</span> given some <span style="color: #00008B;">other event or outcome</span> has already occurred or is in place.</p>
<p>We denote conditional probabilities as <span class="math inline">\(P(outcome | condition)\)</span>.</p>
<p>We can read this as “The probability that outcome occurs <em>given</em> condition is in place”.</p>
<p>We might ask “What’s the probability of a 2.1 mark <em>given</em> the student is in the SES programme?” We’d denote that as:</p>
<p><span class="math display">\[
P(2.1|SES)
\]</span></p>
<table class="table">
<caption>Table 5. When we calculate conditional probabilities we restrict ourselves to one row or column (here coloured) of a contingency table.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 28%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Programme</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grade</strong></td>
<td><span style="color: #5F9EA0;">SES</span></td>
<td>SS</td>
<td><strong>Marginal Total</strong></td>
</tr>
<tr class="even">
<td>1</td>
<td><span style="color: #5F9EA0;">10</span></td>
<td><span style="color: #D3D3D3;">3</span></td>
<td><span style="color: #D3D3D3;">13</span></td>
</tr>
<tr class="odd">
<td>2.1</td>
<td><span style="color: #00BFFF;">20</span></td>
<td><span style="color: #D3D3D3;">6</span></td>
<td><span style="color: #D3D3D3;">26</span></td>
</tr>
<tr class="even">
<td>2.2</td>
<td><span style="color: #5F9EA0;">11</span></td>
<td><span style="color: #D3D3D3;">15</span></td>
<td><span style="color: #D3D3D3;">26</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span style="color: #5F9EA0;;">4</span></td>
<td><span style="color: #D3D3D3;">20</span></td>
<td><span style="color: #D3D3D3;">24</span></td>
</tr>
<tr class="even">
<td><strong>Marginal Total</strong></td>
<td><span style="color: #00008B;">45</span></td>
<td><span style="color: #D3D3D3;">44</span></td>
<td><span style="color: #D3D3D3;">89</span></td>
</tr>
</tbody>
</table>
<p>If we look in the SES column we see 20 students got a 2.1 classification. There were a total of 45 SES students so <span class="math inline">\(P(2.1|SES)\)</span> is <span style="color: #5F9EA0;">20</span>/<span style="color: #00008B;">45</span> or 0.444 or 44.4%.</p>
<p>The general formula for conditional probability is:</p>
<p><span class="math display">\[
P(A|B) = \frac{P(A\text{ and }B)}{P(B)}
\]</span></p>
<p>Let’s see this at work for <span class="math inline">\(P(2.1 | SES)\)</span>.</p>
<p>The joint probability - <span class="math inline">\(P(2.1 \text{ and } SES)\)</span> - is 20/89 = 0.225.</p>
<p>The marginal probability of SES - <span class="math inline">\(P(SES)\)</span> - is 45/89 = 0.506.</p>
<p>The conditional probability of 2.1 given SES (<span class="math inline">\(P(2.1 | SES)\)</span>) is therefore 0.225/0.506 = 0.444; exactly the same as before.</p>
<p><strong>Importantly</strong> <span class="math inline">\(P(A|B) \neq P(B|A)\)</span><strong>.</strong></p>
<p>Examining our contingency table we saw that <span class="math inline">\(P(2.1|SES)\)</span> was 0.444.</p>
<p>However this is not the same as <span class="math inline">\(P(SES|2.1) = \frac{P(2.1 \text{ and } SES)}{P(2.1)}\)</span> = [(20/89) / (26/89)] = 0.77.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Key to conditional probability calculations using a contingency table is that we are <strong>restricting ourselves to one row or column</strong> of the table.</p>
</div>
</div>
</section>
<section id="the-general-multiplication-rule" class="level2">
<h2 class="anchored" data-anchor-id="the-general-multiplication-rule">The General Multiplication rule</h2>
<p>We can rearrange the equation for conditional probability to get the General Multiplication Rule for calculating the joint probability of A <em>and</em> B.</p>
<p><span class="math display">\[
P(A \text{ and } B) = P(A|B)P(B)
\]</span></p>
<p>This is useful if we are not given the joint probability for some outcome.</p>
<p>Maybe we only know that 50.6% of students on the module are on the SES programme and that if a student was on the SES programme the probability of a 2.1. was 44.4%.</p>
<p>We can use this information to work back to the joint probability, <span class="math inline">\(P(2.1 \text{ and } SES\)</span>) using the formula above.</p>
<p><span class="math inline">\(P(2.1 \text{ and } SES) = P(2.1|SES)P(SES))\)</span> = 0.444 * 0.506 = 0.225 - i.e.&nbsp;22.5% as before.</p>
</section>
</section>
<section id="bayes-rule" class="level1 page-columns page-full">
<h1>Bayes rule</h1>

<div class="no-row-height column-margin column-container"><div class="">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://en.wikipedia.org/wiki/Thomas_Bayes"><img src="pics/Thomas_Bayes.gif" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure 1. (Probably not) Thomas Bayes 1701-1761</figcaption><p></p>
</figure>
</div>
<p>Thomas Bayes was a Presbyterian minister &amp; philosopher. Although this portrait is universally used to portray Bayes it is probably <a href="https://www.york.ac.uk/depts/maths/histstat/bayespic.htm">not</a> his portrait. The probability rule we call Bayes rule was published after Bayes’ death by his friend Richard Price in ‘An Essay towards solving a Problem in the Doctrine of Chances’ in 1763.</p>
</div></div><p>We are often given conditional probabilities like <span class="math inline">\(P(2.1 | SES)\)</span> and we actually want the inverse conditional probability, <span class="math inline">\(P(SES|2.1)\)</span>. As we noted above these are <strong>not</strong> the same probabilities!</p>
<p>Bayes rule allows us to invert conditional probabilities.</p>
<p>We know from above that:</p>
<ul>
<li><p><span class="math inline">\(P(A \text{ and } B) = P(A|B)P(B)\)</span></p></li>
<li><p><span class="math inline">\(P(B \text{ and } A) = P(B|A)P(A)\)</span></p></li>
</ul>
<p>We also know that the order of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> in joint probability doesn’t matter:</p>
<p><span class="math inline">\(P(A \text{ and } B) = P(B \text{ and } A)\)</span></p>
<p>This means that:</p>
<p><span class="math display">\[
P(B|A)P(A) = P(A|B)P(B)
\]</span></p>
<p>If we divide through by <span class="math inline">\(P(A)\)</span> we get:</p>
<p><span class="math display">\[
P(B|A) = \frac{P(A|B)P(B)}{P(A)}
\]</span></p>
<p>This is exactly Bayes rule!</p>
<p>If we know <span class="math inline">\(P(A|B)\)</span> and the marginal probabilities, <span class="math inline">\(P(A)\)</span> and <span class="math inline">\(P(B)\)</span> we can get to <span class="math inline">\(P(B|A)\)</span> by applying Bayes rule.</p>
<p>Suppose we know that <span class="math inline">\(P(2.1|SES)\)</span> is 0.444 and we know the marginal probabilities of <span class="math inline">\(P(2.1)\)</span> (0.29) and <span class="math inline">\(P(SES)\)</span> (0.506).</p>
<p>Using Bayes rule we can easily calculate the inverse conditional probability <span class="math inline">\(P(SES|2.1)\)</span>:</p>
<p><span class="math display">\[
P(SES|2.1) = \frac{0.444 \times 0.506}{0.29} = 0.77
\]</span></p>
<p>This is the same result we got above.</p>
<section id="components-of-bayes-rule" class="level2">
<h2 class="anchored" data-anchor-id="components-of-bayes-rule">Components of Bayes rule</h2>
<p>Each part of Bayes rule has a name.</p>
<p>In the numerator <span class="math inline">\(P(A|B)\)</span> is the <em>likelihood</em> and <span class="math inline">\(P(B)\)</span> is the <em>prior</em>. The denominator, <span class="math inline">\(P(A)\)</span> is the <em>marginal probability of A</em> and is also called the <em>evidence</em>. The left hand probability, <span class="math inline">\(P(B|A)\)</span> is called the <em>posterior</em>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pics/Bayes_rule.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure 2. The components of Bayes rule.</figcaption><p></p>
</figure>
</div>
<p>Being able to go from <span class="math inline">\(P(A|B)\)</span> to <span class="math inline">\(P(B|A\)</span>) might seem trivial but it turns out to be really useful.</p>
</section>
</section>
<section id="simple-application-of-bayes-rule" class="level1">
<h1>Simple Application of Bayes rule</h1>
<p>A classic application of Bayes rule is calculating the probability of actually having a disease after a positive test for that disease knowing only:</p>
<ul>
<li>The test result</li>
<li>The disease prevalence rate i.e.&nbsp;the probability of getting the disease</li>
<li>The true positive rate of the test (sensitivity) i.e.&nbsp;the probability the test is positive <em>if you have the disease</em></li>
<li>The true negative rate of the test (specificity) i.e.&nbsp;the probability the test is negative <em>if you do not have the disease</em></li>
</ul>
<p>While I was writing this the COVID-19 prevalence (by positive test) for my age group where I live was 8.8% (<span class="math inline">\(P(COVID)\)</span> = 0.088). It was also the beginning of winter so the flu season was starting up.</p>
<p>Suppose I start feeling unwell and decide to take a lateral flow test to see if I have COVID-19 as opposed to flu (or hopefully just a cold). Lateral flow device true positive rate (<span class="math inline">\(P(+ve|COVID)\)</span>) seems to be pretty good but the true negative rate (<span class="math inline">\(P(-ve|no \text{ } COVID)\)</span>) seems to be much more variable e.g. <span class="citation" data-cites="mistry2021">Mistry et al. (<a href="#ref-mistry2021" role="doc-biblioref">2021</a>)</span>. Let’s say the test I use has a true positive rate of 99% and a true negative rate of 85%.</p>
<p>If I take the test and get a positive result there is a 99% probability the test is correct <strong>if I have COVID-19</strong> i.e.&nbsp;<span class="math inline">\(P(+ve|COVID) = 0.99\)</span>… but this is not what I want to know. If I <em>already knew</em> I had COVID why bother with a test 🤡</p>
<p>What I actually want to know is <span class="math inline">\(P(COVID|+ve)\)</span> i.e.&nbsp;the probability I actually <em>have</em> COVID <em>given</em> the test is positive.</p>
<p>Bayes rule can get us there.</p>
<p><span class="math display">\[
P(COVID|+ve) = \frac{P(+ve|COVID)P(COVID)}{P(+ve)}
\]</span></p>
<p>The numerator is easy from the information we have.</p>
<ul>
<li>Likelihood = <span class="math inline">\(P(+ve|COVID) = 0.99\)</span> i.e.&nbsp;true positive rate</li>
<li>Prior = <span class="math inline">\(P(COVID) = 0.088\)</span> i.e.&nbsp;COVID prevalence</li>
</ul>
<p>The denominator is the sum of the joint probabilities for getting a positive test and there are two ways I can get a positive test.</p>
<ul>
<li>Either I have COVID <em>and</em> the test is positive:</li>
</ul>
<p><span class="math inline">\(P(+ve \text{ and } COVID)\)</span> = <span class="math inline">\(P(+ve|COVID)P(COVID)\)</span> = 0.99 x 0.088 = 0.08712.</p>
<p>Note that this is the same as the numerator; we just applied the general multiplication rule to get a joint probability.</p>
<ul>
<li>Alternatively I can get a false positive result i.e.&nbsp;I do not have COVID <em>but the test is positive anyway</em>.</li>
</ul>
<p>Given the COVID-19 prevalence rate the probability I <em>do not</em> have COVID is 1-0.088 = 0.912.</p>
<p>The test has a false positive rate of 1-0.85 = 0.15.</p>
<p>The joint probability of a positive test and no COVID, <span class="math inline">\(P(+ve \text{ and } not \text{ } COVID)\)</span> is therefore 0.912 x 0.15 = 0.1368.</p>
<p>The denominator for Bayes rule (here <span class="math inline">\(P(+ve)\)</span>) is the sum of these two joint probabilities = <span class="math inline">\(0.08712 + 0.1368\)</span>.</p>
<p>Putting all this together in Bayes rule gives us:</p>
<p><span class="math display">\[
P(COVID|+ve) = \frac{P(+ve|COVID)P(COVID)}{P(+ve)}
\]</span> <span class="math display">\[
P(COVID|+ve) = \frac{0.99 \times 0.088}{0.08712+0.1368}
\]</span> <span class="math display">\[
P(COVID|+ve) = \frac{0.08712}{0.2239}
\]</span> <span class="math display">\[
P(COVID|+ve) = 0.3891
\]</span></p>
<p>So given current prevalence and information about the accuracy of the test there is an approximately 39% chance I actually have COVID after a positive lateral flow test.</p>
<p>We could write a little function to calculate this in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function takes sensitivity, specificity &amp; prevalence</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>bayes_calc <span class="ot">&lt;-</span> <span class="cf">function</span>(sens, spec, prevalance){</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calc numerator</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  numerator <span class="ot">=</span> sens<span class="sc">*</span>prevalance</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calc denom</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  denominator <span class="ot">=</span> numerator <span class="sc">+</span> ((<span class="dv">1</span><span class="sc">-</span>spec) <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>prevalance))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calc prob of disease</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  probDisease <span class="ot">=</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(probDisease)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using this with the figures above for COVID testing gives us:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>prob_pos <span class="ot">&lt;-</span> <span class="fu">bayes_calc</span>(<span class="fl">0.99</span>, <span class="fl">0.85</span>, <span class="fl">0.088</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>prob_pos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3890675</code></pre>
</div>
</div>
<p>Exactly the same result we got from our manual calculation.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Bayes rule is a conditional probability and is derived from simple algebra of established probability rules. Bayes rule allows us to invert conditional probabilities. This in turn can help us address questions like “What’s the probability I have the disease if the test is positive?” rather than simply knowing the probability the test result is right if I have the disease. Questions like the former are often what we really need answers to!</p>
<p>Bayes rule may seem pretty trivial but it is in fact extremely useful. In the examples above the probabilities we used were point probabilities i.e.&nbsp;single numbers but Bayes rule can be used with full probability distributions as well. In the next few posts we’ll explore how using Bayes rule with probability distributions can help us calculate the probability of hypotheses and models as well as estimate effect sizes in statistical analysis. This is where Bayes rule is really useful!</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-mistry2021" class="csl-entry" role="listitem">
Mistry, Dylan A., Jenny Y. Wang, Mika-Erik Moeser, Thomas Starkey, and Lennard Y. W. Lee. 2021. <span>“A Systematic Review of the Sensitivity and Specificity of Lateral Flow Devices in the Detection of SARS-CoV-2.”</span> <em>BMC Infectious Diseases</em> 21 (1): 828. <a href="https://doi.org/10.1186/s12879-021-06528-3">https://doi.org/10.1186/s12879-021-06528-3</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>